export const PRODUCT_CATEGORY_OFFER_NAME_LIST = {
	WATER: [
		'EXTERIOR COMMERCIAL WATER SERVICE LINE',
		'IN-HOME WATER AND GAS LINES REPAIR',
		'WATER SERVICE LINE RESTORATION',
	],
	HEAT: [
		'CUSTOMCARE - HEATING SYSTEM AND WATER HEATER',
		'HEAT PUMP SYSTEM',
		'HEAT PUMP/COOLING',
		'HEAT PUMP/COOLING PLUS',
		'HEAT PUMP/COOLING SYSTEM',
	],
	COOL: [
		'A/C AND HEAT PUMP PLAN',
		'CENTRAL COOLING',
		'COOLING REPAIR',
		'COOLING SYSTEM',
	],
};

export const PRODUCT_CATEGORY_PRODUCT_LINE_LIST: any = {
	WATER: ['WS', 'WV'],
	HEAT: ['HB', 'HI', 'HH', 'HG', 'HN', 'HO', 'HF', 'HP', 'HL'],
	COOL: ['HA', 'HE', 'HW'],
};
